---
# Below config params are used to configure contrailctl
# All of below variables are a dict which form individual section of
# contrailctl/*.conf (controller.conf, agent.conf, etc)
# they are just a dictionary form of config files found under contrailctl/*, where
# control_config is dictionary form of [CONTROL] section in contrailctl/controller.conf
# webui_config is dictionary form of [WEBUI] section in contrailctl/controller.conf

# for example, if one add configuration  "webui_config: {http_listen_port: 8085}",
# [WEBUI] section of contrailctl/controller.conf will be configured as below -
# which infact configure webui to listen 8085 for http instead of 8080
#
# [WEBUI]
# http_listen_port = 8085
#
# For configuration details, please refer example configurations found in
#  https://github.com/Juniper/contrail-docker/tree/master/tools/python-contrailctl/examples/configs/agent.conf
#
##################

#### *** NOTE: Entries in this file can be part of all.yml *** ####

####
# Agent specific config vars these configs will be added to contrailctl/agent.conf
####

# agent_config: agent specific global configs (Configurations under [GLOBAL] section
#    of agent - configs in global_config will be merged to this config,
# i.e contrailctl/agent.conf will have [GLOBAL] section with configs
# added in global_config + agent_config
# agent_config: {}
