---
# Below config params are used to configure contrailctl
# All of below variables are a dict which form individual section of
# contrailctl/*.conf (controller.conf, agent.conf, etc)
# they are just a dictionary form of config files found under contrailctl/*
# i.e below mentioned global_config is a dictionary form of [GLOBAL] section
# in contrailct/*.conf - since this is
#      global_config, they are available to all config files
# where control_config is dictionary form of [CONTROL] section in
# contrailctl/controller.conf
# webui_config is dictionary form of [WEBUI] section in contrailctl/controller.conf
# for example, if one add configuration  "webui_config: {http_listen_port: 8085}",
# [WEBUI] section of contrailctl/controller.conf will be configured as below
# - which infact configure webui to listen 8085 for http instead of 8080 which
# is default
#
# [WEBUI]
# http_listen_port = 8085
#
# REFERENCE: For configuration details, please refer example configurations found in
#  https://github.com/Juniper/contrail-docker/tree/master/tools/python-contrailctl/examples/configs/analytics.conf
#

# *** NOTE: Entries in this file can be part of all.yml *** ####

#
# Analytics specific config vars - this will be added to contrailctl/analytics.conf
#
# analytics_config: analytics specific global configs - contrailctl/analytics.conf
# will have [GLOBAL] section with configs added in global_config + analytics_config
# analytics_config: {}

# alarm_gen_config: config params for alarm_gen - these will go to [ALARM_GEN]
# section of contrailctl/analytics.conf
# alarm_gen_config: {}

# analytics_api_config: config params for analytics_api - these will go to
# [ANALYTICS_API] section of contrailctl/analytics.conf
# analytics_api_config: {}

# analytics_collector_config: config params for analytics_collector - these
# will go to [ANALYTICS_COLLECTOR] section of contrailctl/analytics.conf
# analytics_collector_config: {}

# query_engine_config: config params for query_engine - these will go to
# [QUERY_ENGINE] section of contrailctl/analytics.conf
# query_engine_config: {}

# snmp_collector_config: config params for snmp_collector - these will go
# to [SNMP_COLLECTOR] section of contrailctl/analytics.conf
# snmp_collector_config: {}

# topology_config: config params for topology - these will go to [TOPOLOGY]
# section of contrailctl/analytics.conf
# topology_config: {}
