---
- name: allow unauthenticated packages for ubuntu
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99allowunauth owner=root group=root mode=0644

- name: install policy-rc.d to selectively disable automated service start by apt
  copy: src=policy-rc.d dest=/usr/sbin/policy-rc.d mode=0755

# This is a workaround on issue https://github.com/Juniper/contrail-docker/issues/107
- name: Add systemd-logind to /etc/sensitive_servies (WA for issue contrail-docker/107)
  lineinfile: dest=/etc/sensitive_services line="{{ item_service }}" state=present create=yes
  with_items:
    - systemd
    - systemd-logind
    - rabbitmq-server
  loop_control:
    loop_var: item_service
  when: contrail_service_mgr != 'systemd'

- name: Run apt-get update
  apt: update_cache=yes
  when: apt_update
  ignore_errors: yes
