---
- name: "Copy contrailctl/analyticsdb.conf"
  copy: src={{ item }} dest={{ contrailctl_config_directory }}
  with_first_found:
    - files:
      - "{{ contrailctl_config_source |ternary(contrailctl_config_source + '/analyticsdb.conf', 'contrailctl/analyticsdb.conf') }}"
      - contrailctl/analyticsdb.conf
      - "{{ playbook_dir }}/contrailctl/analyticsdb.conf"
      - /etc/contrailctl/analyticsdb.conf
      skip: true
