---
- name: Copy contrail apt repo image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_repo_ubuntu_image_archive }}"
    dest: "/tmp/{{ contrail_repo_ubuntu_image_archive }}"
  when: docker_registry is not defined or load_contrail_repo_ubuntu_image is defined

- name: "Load contrail apt repo image"
  docker_image:
    name: "contrail-repo-{{ os_release }}"
    tag: "{{ contrail_version }}"
    timeout: "{{ container_image_load_timeout }}"
    load_path: "/tmp/{{ contrail_repo_ubuntu_image_archive }}"
  when: docker_registry is not defined  or load_contrail_repo_ubuntu_image is defined

- name: Launch apt repo container
  docker_container:
    name: "contrail-repo-{{ os_release }}"
    image: "{{ contrail_repo_ubuntu_image }}"
    network_mode: host
    state: started
    pull: "{{ always_pull_image }}"
    tty: true
