---
docker_ssl_key_pki_cacert_dir : /etc/pki/ca-trust/source/anchors
docker_ssl_key_pki_cert_dir : /etc/pki/tls/certs
docker_ssl_key_pki_key_dir : /etc/pki/tls/private

docker_options_var: OPTIONS
docker_env_file: "{{ '/etc/sysconfig/docker' if ansible_distribution != 'RedHat' else '/etc/docker/daemon.json' }}"
