---
- name: Copy contrail mesos_manager image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_mesos_manager_image_archive }}"
    dest: "/tmp/{{ contrail_mesos_manager_image_archive }}"
  when: docker_registry is not defined or load_contrail_mesos_manager_image is defined

- name: "Load contrail mesos_manager image"
  docker_image:
    name: contrail-mesos-manager
    tag: "{{ contrail_version }}"
    timeout: "{{ container_image_load_timeout }}"
    load_path: "/tmp/{{ contrail_mesos_manager_image_archive }}"
  when: docker_registry is not defined  or load_contrail_mesos_manager_image is defined

- name: Configure contrailctl/mesosmanager.conf
  include: "contrailctl/mesosmanager/{{ contrailctl_config_mode }}.yml"

- name: "Start contrail mesos_manager container"
  docker_container:
    name: contrail-mesos-manager
    image: "{{ contrail_mesos_manager_image }}"
    network_mode: host
    state: started
    tty: true
    pull: "{{ always_pull_image }}"
    privileged: true
    restart_policy: unless-stopped
    volumes:
      - "{{ contrailctl_config_directory }}:/etc/contrailctl/"
